### ISSUE TITLE
Cannot resolve symbol - php_namespace

### ISSUE THREAD

**Issue by SonicGD** [protostuff/protobuf-jetbrains-plugin#100]
Hello. I have problem in Rider 2018.1 with php_namespace option.

```proto
syntax = "proto3";
package Foo.Bar;
option csharp_namespace = "Foo.Bar";
option swift_prefix = "Foo\\Bar";

message Baz {
    int32 BazId = 1;
}
```

![image](https://user-images.githubusercontent.com/1222013/41956871-91ec49f8-79fe-11e8-8a46-352ce40f360d.png)

If i change it to, for example, java_outer_classname - errors dissappears. 

Extensions version - v.0.10.2

**Comment by kshchepanovskyi** [comment]
While it is not published yet, you may try https://jenkins.ksprojects.org/job/protostuff/job/protobuf-jetbrains-plugin/job/master/6/artifact/build/distributions/protobuf-jetbrains-plugin-0.10.2.zip - I would appreciate any feedback.
