### ISSUE TITLE
block comment should insert * when pressing enter

### ISSUE THREAD

**Issue by jorgheymans** [protostuff/protobuf-jetbrains-plugin#101]
inside of a block comment, when i press enter to start a new line it would be nice if the '*' character is inserted automatically, much like editing a javadoc in IntelliJ.

**Comment by swiesner-dlr** [comment]
I'd also appreciate this change; it'd make documnetation comments for protobuf files much easier :smiley:

**Comment by kshchepanovskyi** [comment]
This issue is closed as plugin is not supported anymore. 
Please switch to https://github.com/jvolkman/intellij-protobuf-editor.
