### ISSUE TITLE
Imports not working properly

### ISSUE THREAD

**Issue by cisaacson** [protostuff/protobuf-jetbrains-plugin#105]
Thanks for offering your Protobuf plugin for Webstorm.

The plugin is not finding files in import statements (see below). The files are definitely there, the google files are on the path and the ‘test2.proto’ is in the same folder as the .proto I am editing. Everything compiles fine when I generate code from the .proto files so I know they are correct.

```
syntax = "proto3";

import "google/protobuf/any.proto";
import "google/protobuf/timestamp.proto";
import "./rt-enum.proto";
```

**Comment by cwei-bgl** [comment]
@kshchepanovskyi Hi, Thanks for the plugin. why this issue is closed? I just came across this and it is not working. was this already implemented in Milestone 0.11? Thanks.
