### ISSUE TITLE
Reformatting protobuf files adds extra spaces

### ISSUE THREAD

**Issue by dlsniper** [protostuff/protobuf-jetbrains-plugin#107]
What steps will reproduce the issue?
1. Create a protobuf file.
2. Add an RPC to a service, such as `rpc Add(AddRequest) returns (AddResponse);`.
3. Choose Reformat Code.

What is the expected result?
No change to the line as it appears above.

What happens instead?
A space is added before the request parameter: `rpc Add (AddRequest) returns (AddResponse);`

This appears to be in contradiction to the style guide: https://developers.google.com/protocol-buffers/docs/style

Original issue at: https://youtrack.jetbrains.com/issue/GO-6156

**Comment by kshchepanovskyi** [comment]
This issue is closed as plugin is not supported anymore. 
Please switch to https://github.com/jvolkman/intellij-protobuf-editor.
