### ISSUE TITLE
Advanced formatter settings

### ISSUE THREAD

**Issue by kshchepanovskyi** [protostuff/protobuf-jetbrains-plugin#11]
Formatter settings (added in release [0.3.0](https://github.com/protostuff/protostuff-jetbrains-plugin/milestones/0.3.0)) are very basic, only indentation can be configured.
I did not add any additional settings as it was not clear if it is needed to anybody.

**If you need any additional formatter settings, please leave comments here.**

**Comment by zhYou** [comment]
thank you for this great plugin, and forgive my poor English.

```
/*
    Message Comment
*/
message MyMessage {
    required int64 field            = 1; // field comment
    required int32 long_field       = 2; // field comment
    required string long_long_field = 3; // field comment
}

```
Can you support this style?

**Comment by kshchepanovskyi** [comment]
Yes, it can be supported. A setting to preserve spaces before `=` can be added. 

I will gladly accept a pull request with this functionality :)

**Comment by nhooyr** [comment]
I think it would be great to support the following style:

```proto
message IssueCertRequest {}
```

Right now, these messages are formatted as

```proto

message IssueCertRequest {
}
```

**Comment by kshchepanovskyi** [comment]
Feel free to make a pull request ;)

**Comment by kshchepanovskyi** [comment]
This issue is closed as plugin is not supported anymore. 
Please switch to https://github.com/jvolkman/intellij-protobuf-editor.
