### ISSUE TITLE
Support for service / rpc options

### ISSUE THREAD

**Issue by pkwarren** [protostuff/protobuf-jetbrains-plugin#110]
**Is your feature request related to a problem? Please describe.**
Currently, the protobuf plug-in doesn't appear to understand options defined on either the service level or rpc (method) level. 

**Describe the solution you'd like**
The [protobuf v3 spec](https://developers.google.com/protocol-buffers/docs/reference/proto3-spec#service_definition) allows for options defined at the service and rpc (method) level.

**Additional context**
Example (using Google's http.proto): https://github.com/googleapis/googleapis/blob/2a57c3158a97597941220e64a940760d6a738a69/google/api/http.proto#L129-L136

When using the plug-in today, I get various errors when using service or rpc options:

* When using a built-in option, I get an error regarding an unresolved reference (this reference should be found in the descriptor.proto file):

```proto
service MyService {
    option idempotency_level = NO_SIDE_EFFECTS;
    ...
}
```

* When using a custom option, I get an error regarding extraneous input (after the semicolon in the option):

```proto
service MyService
    option (company.grpc.custom_rule) = {
        my_field: "abc"; // Error after semicolon here
        my_list_field: ["a", "b", "c"];
    };
    ...
}
```

**Comment by kshchepanovskyi** [comment]
Regarding first one - `idepmotency_level` is method's option, it's not applicable for service: https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/descriptor.proto#L684

**Comment by kshchepanovskyi** [comment]
For second one - AFAIK it should look like this:

```proto
service MyService {
    option (company.grpc.custom_rule) = {
            my_field: "abc"
            my_list_field: "a"
            my_list_field: "b"
            my_list_field: "c"
    };
}
```

When you use `{}` for field/method level options, you should use "protobuf text format" inside of the block.

- https://stackoverflow.com/questions/18873924/what-does-the-protobuf-text-format-look-like
- https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/unittest_custom_options.proto#L350

**Comment by kshchepanovskyi** [comment]
Can you please check if `protoc` compiles your examples?

**Comment by pkwarren** [comment]
I've verified that using Protobuf text format works as expected. This also fixes the parsing for options coming from descriptor.proto. Feel free to close this - it was confusing at first to have protoc allow this syntax and not the plug-in.

**Comment by kshchepanovskyi** [comment]
> Protoc does compile the custom method options as written. 

In this case I'll keep it open - at some point plugin should support this syntax as well.

**Comment by pkwarren** [comment]
Try:

```proto
syntax="proto3";

import "google/protobuf/descriptor.proto";
import "google/protobuf/empty.proto";

message CustomOptions {
    string my_field = 1;
    repeated string my_list_field = 2;
}

extend google.protobuf.ServiceOptions {
    CustomOptions custom_rule = 50003;
}

service MyService {
    option (custom_rule) = {
        my_field: "abc";
        my_list_field: ["a", "b", "c"];
    };
    rpc Get(google.protobuf.Empty) returns(google.protobuf.Empty) {}
}
```

**Comment by pkwarren** [comment]
Here's a full example Maven project - https://www.dropbox.com/s/avs1aeirk834qf9/example.tar.gz?dl=0

When expanded, you can run `mvn compile` to generate the Java code and service from the proto file. The `DescriptorTest` program can be executed to show the service options are parsed as expected from the proto file.

**Comment by kshchepanovskyi** [comment]
I see, you replaced `=` to `:`, now it compiles - so semicolons and lists inside of square brackets are supported. Thanks!

**Comment by yinzara** [comment]
When loading the following protobuf file in IntelliJ, multiple errors occur related to the structured options.
https://github.com/grpc-ecosystem/grpc-gateway/blob/master/examples/proto/examplepb/a_bit_of_everything.proto

As soon as a single error is detected, the rest of the file does not parse at all causing syntax highlighting to just stop functioning.

**Comment by abonec** [comment]
Do you have any status about the issue? Plugin does not support grpc.gateway.protoc_gen_swagger.options.openapiv2_swagger at all as mentioned above.

**Comment by kshchepanovskyi** [comment]
Checking...

**Comment by yinzara** [comment]
For the grpc.gateway.protoc_gen_swagger.options you either need to copy the "a_bit_of_everything.proto" to the root of the grpc-gateway project and open the project in IntelliJ or you need to add a "Custom Include Path" to the Protobuf plugin config to the root of the grpc-gateway project.  However even when doing that, the file shows multiple errors.

**Comment by frennkie** [comment]
> you need to add a "Custom Include Path" to the Protobuf plugin config

I wasn't aware of this.. thanks.

Stil,l I have same problem that I get an error on the semi-colon (after ` "go-ws-api";`) and on the next line on the first word (`version`). The files compile without any issue.

``` 
syntax = "proto3";
package echopb;

import "google/api/annotations.proto";
import "protoc-gen-swagger/options/annotations.proto";

option (grpc.gateway.protoc_gen_swagger.options.openapiv2_swagger) = {
    info: {
        title: "go-ws-api";
        version: "1.0";
        contact: {
            name: "go-ws-api";
            url: "https://github.com/mch1307/ws-go-api";
            email: "none@example.com";
        };
    };
    schemes: HTTP;
    schemes: HTTPS;
    consumes: "application/json";
    produces: "application/json";
};

message EchoMessage {
 string value = 1;
}

service EchoService {
  rpc Echo(EchoMessage) returns (EchoMessage) {
    option (google.api.http) = {
      post: "/v1/echo"
      body: "*"
    };
  }
}
```

Code mostly take from: https://blog.csnet.me/blog/building-a-go-api-grpc-rest-and-openapi-swagger.1/

It would be great if this could be fixed in the plugin! :-D

**Comment by Dasio** [comment]
Any info regarding this issue? This should be valid proto file [A bit of everything](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/examples/proto/examplepb/a_bit_of_everything.proto).

**Comment by kshchepanovskyi** [comment]
This issue is closed as plugin is not supported anymore. 
Please switch to https://github.com/jvolkman/intellij-protobuf-editor.
