### ISSUE TITLE
Comment changes on refactor

### ISSUE THREAD

**Issue by sirkon** [protostuff/protobuf-jetbrains-plugin#111]
**Is your feature request related to a problem? Please describe.**
At my job we demand comments on every item (message, enum, service, rpc method, field) starting from item name, it looks like

```proto
// Object - object representation for end-user (there's also internal DBObject)
message Object {
}
```

**Describe the solution you'd like**
It would be nice if refactoring would propose comment changes as well

**Additional context**
We derived this comment convention from Golang. In GoLand they (JetBrains) propose comment modifications. See the screencast.

![screencast_07 09 2018_16_48_41](https://user-images.githubusercontent.com/56399/45222885-60102000-b2be-11e8-8ce4-3897a2eeafc2.gif)

**Comment by kshchepanovskyi** [comment]
This issue is closed as plugin is not supported anymore. 
Please switch to https://github.com/jvolkman/intellij-protobuf-editor.
