### ISSUE TITLE
Imported .proto files not found

### ISSUE THREAD

**Issue by daczczcz1** [protostuff/protobuf-jetbrains-plugin#113]
**Describe the bug**
Imported .proto file not recognized (cannot navigate to messages defined in that file).

**To Reproduce**
1. Create a .proto file with a message defined in it.
2. Create another .proto file in the same directory and with the same package and import the first one
3. Try to use the message defined in the first file

4. Imported file not recognized, message (while hovering on file name): "File not found". None of the messages defined in it are accessible (for code completion, navigation etc.).

**Expected behavior**
File imported, its content accessible.

**Plugin (please complete the following information):**
 - OS: Windows 10 Enterprise 
 - Version 0.10.2
- Intellij IDEA version: 2018.1

**Comment by kshchepanovskyi** [comment]
Hi, this issue has been resolved in plugin version 0.11.0. New version is compatible with IDEA 2018.2+.

**Comment by daczczcz1** [comment]
Thank you, will try 0.11.0 then.
