### ISSUE TITLE
Multiline string marked red

### ISSUE THREAD

**Issue by nathanmbrown** [protostuff/protobuf-jetbrains-plugin#121]
**Describe the bug**
A multiline string value is supported by Protobuf but marked red

**To Reproduce**
Add multiline text e.g.
```
  description:
    "this\n"
    "would\n"
    " naturally be a\n"
    " multiline string"
```

**Expected behavior**
The string is shown as valid

**Screenshots**
`"would\n"` is marked as in error

**Comment by armiol** [comment]
I have encountered this issue as well. Its root seems to be in the `ProtoParser.g4` grammar definition from the `protostuff-parser` dependency. The option value is defined as 
```
optionValue
    : INTEGER_VALUE
    | FLOAT_VALUE
    | BOOLEAN_VALUE
    | STRING_VALUE
    | IDENT
    | textFormat
    ;
```
and `STRING_VALUE` does not seem to support multiline string literals.

BTW @kshchepanovskyi I wasn't able to find the source code for the 2.2.26 release of `protostuff-parser` — [its `master` branch](https://github.com/protostuff/protostuff/tree/master/protostuff-parser) seems to be really outdated. So I am not even able to help with the PR to resolve the issue. Could you please point to the up-to-date sources?

**Comment by kshchepanovskyi** [comment]
Hi @armiol,

It's in different repo, https://github.com/protostuff/protostuff-compiler

**Comment by kshchepanovskyi** [comment]
Grammar is here: https://github.com/protostuff/protostuff-compiler/tree/master/protostuff-parser/src/main/antlr4/io/protostuff/compiler/parser

**Comment by kshchepanovskyi** [comment]
This issue is closed as plugin is not supported anymore. 
Please switch to https://github.com/jvolkman/intellij-protobuf-editor.
