### ISSUE TITLE
Support `required` keyword

### ISSUE THREAD

**Issue by Jeff-Tian** [protostuff/protobuf-jetbrains-plugin#122]
Highlight the keyword `required`.

Currently the keyword `required` is not supported, and shows an error message:

```
Field Label 'required' is not allowed.
```

![image](https://user-images.githubusercontent.com/3367820/47404104-975b6300-d77e-11e8-993c-1d55b41b48b4.png)

**Comment by kshchepanovskyi** [comment]
Required fields are not supported in proto3.

- https://developers.google.com/protocol-buffers/docs/proto3

**Comment by Jeff-Tian** [comment]
Thanks @kshchepanovskyi
