### ISSUE TITLE
More effective syntax support with "import".

### ISSUE THREAD

**Issue by STRRL** [protostuff/protobuf-jetbrains-plugin#123]
**Is your feature request related to a problem? Please describe.**

Related to this error: `Backslashes, consecutive slashes, ".", or ".." are not allowed in the virtual path`.

Here are 2 proto file:
src/main/proto/model/MyEnum.proto
```protobuf
enum MyEnum{
    FOO = 0;
    BAR = 1;
}
```
src/main/proto/FoobarService.proto
```protobuf
import "./model/MyEnum.proto";

service FoobarService{
    rpc simpleRpc (MyEnum) returns (UnimportentMessage) {
        
    }
}

message UnimportentMessage{
}
```

It will not worked well with `mvn protobuf:compile`.

**Describe the solution you'd like**
Please mark path red if  it contains `Backslashes, consecutive slashes, ".", or ".."`

**Comment by kshchepanovskyi** [comment]
This issue is closed as plugin is not supported anymore. 
Please switch to https://github.com/jvolkman/intellij-protobuf-editor.
