### ISSUE TITLE
Not generating sources on build/rebuild project

### ISSUE THREAD

**Issue by daviderickson** [protostuff/protobuf-jetbrains-plugin#128]
**Describe the bug**
When I change my proto file, then within IntelliJ click [Re]Build-project, my sources are not regenerated.  To get them to regenerate I have to manually right click on the project and go to Maven -> Generate Sources and Update Folders

**To Reproduce**
Very simple Maven project with the following configuration in the POM:
```
  <build>
    <!-- GRPC related -->
      <resources>
          <resource>
              <directory>src/main/proto</directory>
          </resource>
      </resources>
    <extensions>
      <extension>
          <groupId>kr.motd.maven</groupId>
          <artifactId>os-maven-plugin</artifactId>
          <version>1.5.0.Final</version>
      </extension>
    </extensions>
<plugins>
        ... other plugins here ...
        <plugin>
            <groupId>org.xolstice.maven.plugins</groupId>
            <artifactId>protobuf-maven-plugin</artifactId>
            <version>0.6.1</version>
            <configuration>
                <protocArtifact>com.google.protobuf:protoc:3.5.1-1:exe:${os.detected.classifier}</protocArtifact>
                <pluginId>grpc-java</pluginId>
                <pluginArtifact>io.grpc:protoc-gen-grpc-java:1.17.1:exe:${os.detected.classifier}</pluginArtifact>
            </configuration>
            <executions>
                <execution>
                    <goals>
                        <goal>compile</goal>
                        <goal>compile-custom</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
</plugins>
```
Proto file is in src/main/proto/

**Expected behavior**
I'd expect ideally upon file save of a proto to rebuild, or worst case the explicitly run build or rebuild project and to have them regenerated.

**Plugin (please complete the following information):**
 - OS: Windows 10
 - Plugin version: 0.12.0
 - IDE: IntelliJ iDEA 2018.2.4

**Additional context**
Please let me know if I am way off base here, or if I've set something totally wrong.  Thanks!

**Comment by kshchepanovskyi** [comment]
This issue is closed as plugin is not supported anymore. 
Please switch to https://github.com/jvolkman/intellij-protobuf-editor.
