### ISSUE TITLE
Missing field name does not show an error marker when using proto3 syntax.

### ISSUE THREAD

**Issue by BalzGuenat** [protostuff/protobuf-jetbrains-plugin#131]
**Describe the bug**
While using proto3 syntax, there is no error marker if the field name is missing.

**To Reproduce**
Write a message type like so:
```
syntax = "proto3";
message Foo {
  string = 1;
}
```

**Expected behavior**
An error marker (e.g. red squiggly underline) should be shown at the incomplete field declaration, just like it does with proto2 syntax.

**Screenshots**
https://i.imgur.com/Bounohi.png

**Plugin:**
 - OS: Windows 10
 - Plugin version: 0.12.0
 - IDE: IntelliJ iDEA 2018.3.4

**Comment by kshchepanovskyi** [comment]
This issue is closed as plugin is not supported anymore. 
Please switch to https://github.com/jvolkman/intellij-protobuf-editor.
