### ISSUE TITLE
Incompatible with IntelliJ 2019.1 beta

### ISSUE THREAD

**Issue by reitzmichnicht** [protostuff/protobuf-jetbrains-plugin#133]
**Describe the bug**
Latest plugin version:

> 2019-03-07 11:17:59,261 [ 317275]  ERROR - tartup.impl.StartupManagerImpl - Method com.intellij.openapi.roots.impl.libraries.ProjectLibraryTable.getInstance(Lcom/intellij/openapi/project/Project;)Lcom/intellij/openapi/roots/libraries/LibraryTable; must be InterfaceMethodref  
> java.lang.IncompatibleClassChangeError: Method com.intellij.openapi.roots.impl.libraries.ProjectLibraryTable.getInstance(Lcom/intellij/openapi/project/Project;)Lcom/intellij/openapi/roots/libraries/LibraryTable; must be InterfaceMethodref 
> 	at io.protostuff.jetbrains.plugin.ProtostuffPluginController.findGlobalProtobufLibrary(ProtostuffPluginController.java:171)
> 	at io.protostuff.jetbrains.plugin.ProtostuffPluginController.updateGlobalLibrary(ProtostuffPluginController.java:140)
> 	at io.protostuff.jetbrains.plugin.ProtostuffPluginController.projectOpened(ProtostuffPluginController.java:87)
> 

**To Reproduce**
- Happens on IDE startup

**Comment by kshchepanovskyi** [comment]
Fixed in 0.13.0
