### ISSUE TITLE
can not use this plugin

### ISSUE THREAD

**Issue by stanpcf** [protostuff/protobuf-jetbrains-plugin#134]
**Describe the bug**
![image](https://user-images.githubusercontent.com/13925796/54415609-bbbcd980-4737-11e9-91e9-84ecaf553f78.png)
the plugin can not use. I have restart pycharm.

**To Reproduce**
the first time I download this protobuf plugin, the Event Log give a log about the plugin installed successful, and the `person.proto` change the icon from plant text to a proto icon. While the Event plugin have a button `revert`. then I clicked, emmm, then the plugin is useless, even if I reinstall and restart many times

**Plugin (please complete the following information):**
- PyCharm 2018.3.5 (Professional Edition)
Build #PY-183.5912.18, built on February 26, 2019
JRE: 1.8.0_152-release-1343-b28 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
 - OS: macOS Mojave 10.14.3
 - Plugin version: v0.13.0

**Comment by kshchepanovskyi** [comment]
Interesting, it might be that *.proto files are not associated with plugin.
Please check settings in Editor -> File Types, Protobuf:

![image](https://user-images.githubusercontent.com/4040120/54459642-ed519700-476f-11e9-95ab-272ace737573.png)

It should contain `*.proto` pattern.

**Comment by stanpcf** [comment]
@kshchepanovskyi thank you for your reply. it's a good resolution 👍
