### ISSUE TITLE
Error when using square brackets in third party extension

### ISSUE THREAD

**Issue by ethiery** [protostuff/protobuf-jetbrains-plugin#136]
**Describe the bug**
The plugin currently highlights closing brackets in extensions as errors.

**To Reproduce**
I came across this bug using [protoc-gen-validate](https://github.com/lyft/protoc-gen-validate)
1. [Install protoc-gen-validate](https://github.com/lyft/protoc-gen-validate#installation)
2. Add `$GOPATH/src/github.com/lyft/protoc-gen-validate` to include paths of the plugin.
3. Open any protobuf definition file using brackets in an extension, such as:
```
syntax = "proto3";

import "validate/validate.proto";

package myproto;

message MyMessage {
    MyEnum enum = 1 [(validate.rules).enum = {not_in: [0]}];
}

enum MyEnum {
    ZERO = 0;
    ONE = 1;
}
```

**Expected behavior**
No syntax error.

**Screenshots**
![image](https://user-images.githubusercontent.com/13584434/55324112-0305d280-5479-11e9-9544-232ba7ec3a1d.png)

**Plugin (please complete the following information):**
 - OS: Ubuntu 18.04
 - Plugin version: 0.13.0
 - IDE: GoLang 2019.1 / IntelliJ iDEA Ultimate 2019.1

**Comment by mennanov** [comment]
I also get a similar error with the following proto:

```
message RegisterRequest {
    string username = 1 [(shared.proto.validator.field) = {regex: "^[a-z0-9_]{3,32}$"}];  // <- OK here
    string email = 2 [(shared.proto.validator.field) = {regex: "^.+@.+$", length_lt: 101}]; // error here
    string password = 3 [(shared.proto.validator.field) = {msg_exists: true, length_gt: 7}]; // also an error here
}
```

The plugin incorrectly complains about the "," symbol: `<missing '}'>` and then it fails to parse everything that follows this comma.

**Comment by vwagner** [comment]
Even worse: if you then try to reformat the code in this case, you end up with a severely jumbled file, with one symbol per line 
<img width="225" alt="Screen Shot 2019-10-16 at 3 28 08 PM" src="https://user-images.githubusercontent.com/2718509/66960399-9a9fcc80-f029-11e9-82c5-ae540f998771.png">

**Comment by nonpcnpc** [comment]
I think this is the same issue. Second line always gets me error(the foo.bar errors only because it is non existent example):
![foobar](https://user-images.githubusercontent.com/3159095/67416084-78c4bd80-f5c6-11e9-8c5a-074991d85f96.png)

**Comment by kshchepanovskyi** [comment]
This issue is closed as plugin is not supported anymore. 
Please switch to https://github.com/jvolkman/intellij-protobuf-editor.
