### ISSUE TITLE
Support Color Theming for Message Type & Field Type Declarations

### ISSUE THREAD

**Issue by kvnxiao** [protostuff/protobuf-jetbrains-plugin#137]
**Is your feature request related to a problem? Please describe.**
Currently the plugin doesn't support setting a different colour for the message type-naming, so it is difficult to read and differentiate between field type vs name of field.

e.g.

```proto
message A {
    ...
}

message B {
    A a = 1;
}
```

On GitHub, the message types `A` and `B` are highlighted in a blue colour, which differentiates it from the `a` field name declaration.

In Jetbraints products, both `A` and `a` are the same colour.

![image](https://user-images.githubusercontent.com/14130413/55522940-d221cb00-563b-11e9-859a-89a9c695036c.png)

**Describe the solution you'd like**
Add support to colour the message type declarations and subsequently the field types as well, to differentiate colours between type vs name.

**Comment by kshchepanovskyi** [comment]
This issue is closed as plugin is not supported anymore. 
Please switch to https://github.com/jvolkman/intellij-protobuf-editor.
