### ISSUE TITLE
Returning a primitive type does not show an error

### ISSUE THREAD

**Issue by russoj88** [protostuff/protobuf-jetbrains-plugin#138]
The plugin does not recognize the following as an error.  Services cannot return primitive types.
```protobuf
syntax = "proto3";

package proto;

service MyService {
    rpc Serve (MyMsg) returns (bool);
}

message MyMsg {
    string me = 1;
}
```

 - OS: LinuxMint 19.1
 - Plugin version: v0.13.0
 - IDE: GoLand Nightly
Build #GO-191.6183.112, built on April 3, 2019
JRE: 1.8.0_202-release-1483-b39 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-47-generic

**Comment by kshchepanovskyi** [comment]
This issue is closed as plugin is not supported anymore. 
Please switch to https://github.com/jvolkman/intellij-protobuf-editor.
