### ISSUE TITLE
Add support for multiline strings

### ISSUE THREAD

**Issue by maguro** [protostuff/protobuf-jetbrains-plugin#139]
I am shepherding a change in Protobufs to allow multi-line string values:

https://github.com/protocolbuffers/protobuf/issues/1297
https://github.com/protostuff/protostuff-compiler/issues/60

This ticket serves as a marker for the corresponding effort required in this project.  I have forked this project and gotten a working version on my fork.  I'll submit a PR once things start solidifying in the protobuf project.

**Comment by maguro** [comment]
Looking good...

<img width="1170" alt="Screen Shot 2019-04-23 at 1 03 49 AM" src="https://user-images.githubusercontent.com/165060/56564857-d74fa700-6563-11e9-821d-0b6abe386447.png">

**Comment by maguro** [comment]
The plugin is aware of two kinds of strings, ones that are for string values and ones that are for string names, e.g. import paths:

<img width="886" alt="Screen Shot 2019-04-23 at 6 57 47 AM" src="https://user-images.githubusercontent.com/165060/56586928-76d95d80-6595-11e9-87b9-b0615db7db6e.png">

When a string value is used somewhere a string name is required, the proper error occurs:

<img width="752" alt="Screen Shot 2019-04-23 at 6 58 30 AM" src="https://user-images.githubusercontent.com/165060/56587071-bef88000-6595-11e9-883f-2b99c47cdadb.png">

**Comment by kshchepanovskyi** [comment]
This issue is closed as plugin is not supported anymore. 
Please switch to https://github.com/jvolkman/intellij-protobuf-editor.
