### ISSUE TITLE
Can not support IDEA 2018.3.5

### ISSUE THREAD

**Issue by arjenzhou** [protostuff/protobuf-jetbrains-plugin#141]
**Describe the bug**

It does not work for IDEA 2018.3.5, I have tried reinstall a few times and it did not work with `.proto` files.

I have tried to set dir as sources root and as README.md, but it didn't work, either.

**Screenshots**
![img1](https://i.loli.net/2019/05/14/5cdad2013105e40335.png)
![img2](https://i.loli.net/2019/05/14/5cdad2566680946732.png)

**Plugin (please complete the following information):**
 - OS: Windows 10
 - Plugin version: 0.13.0
 - IDE: IntelliJ iDEA 2018.3

**Comment by kshchepanovskyi** [comment]
It might be related to https://github.com/protostuff/protobuf-jetbrains-plugin/issues/134#issuecomment-473427006

**Comment by arjenzhou** [comment]
Thanks for your reply, though I didn't use windows any more. It works on Ubuntu.
