### ISSUE TITLE
Rider support? 

### ISSUE THREAD

**Issue by daveyostcom** [protostuff/protobuf-jetbrains-plugin#142]
I guess I'm the first one to ask for support in Rider on Mac.

**Comment by kshchepanovskyi** [comment]
It should work already, there's more than thousand downloads from Rider IDE of latest plugin version (0.13.0).

Do you have issues with plugin installation?

**Comment by daveyostcom** [comment]
Your ReadMe mentions only Java. Rider as you know is for C#. Can you add something to the ReadMe that would explain what it does with Java and whether it does the same in Rider with C#? Thanks.

**Comment by florian-talos** [comment]
I am using this in Rider. The UI of Rider is written in Java (it's the IntelliJ IDEA shell) and it's talking to a Resharper C# process to do its magic.

**Comment by su-rabbit** [comment]
Yes, All feature is working normally.

**Comment by kshchepanovskyi** [comment]
This issue is closed as plugin is not supported anymore. 
Please switch to https://github.com/jvolkman/intellij-protobuf-editor.
