### ISSUE TITLE
Support nested annotation syntax

### ISSUE THREAD

**Issue by F21** [protostuff/protobuf-jetbrains-plugin#143]
**Describe the bug**
I am using https://github.com/envoyproxy/protoc-gen-validate to generate validators for my protobuf using annotations.

Both of the following are valid syntax and compiles properly, but is considered to be invalid by the protobuf plugin:

Formatted by https://github.com/uber/prototool
```protobuf
message SomeMessage {
  repeated string ids = 1 [
    (validate.rules).repeated = {
      items: {
        string: {
          len: 36
        }
      }
      min_items: 1
    }
  ];
}
```

In a single line:
```protobuf
message SomeMessage {
  repeated string ids = 1 [(validate.rules).repeated = {items {string {len: 36}}, min_items: 1}];
}
```

**To Reproduce**
1. Paste the above snippets into the editor and see errors being highlighted.

**Expected behavior**
The above snippets are valid and should not be considered errors

**Screenshots**
![err](https://user-images.githubusercontent.com/2263040/58675001-b7e33f80-8395-11e9-8e79-5af00513d9ef.png)

**Plugin (please complete the following information):**
 - OS: Windows 10 May Update
 - Plugin version: v0.13.0
 - IDE: GoLand 2019.1.3

**Comment by themontem** [comment]
+1

**Comment by jvolkman** [comment]
These expanded option values are just embedded text protos, so properly supporting the syntax requires adding support for protobuf text format which is a sizable undertaking.

You can try the plugin at https://github.com/jvolkman/intellij-protocol-buffer-editor which does support this (shameless plug since development seems to have slowed here).

**Comment by bjaglin** [comment]
This does not mention arrays (to express values of repeated fields in options), but support is also lacking.

The current parser only supports scalar literal for option values, but a literal can be a map or an array of literals (recursively).

```
syntax = "proto2";

// https://raw.githubusercontent.com/envoyproxy/protoc-gen-validate/dbe039e/validate/validate.proto
import "validate/validate.proto";

message foo {
	optional int64 bar = 1 [(validate.rules).int64 = { gte: 42 }]; //OK
	optional int64 baz = 2 [(validate.rules) = { int64: { gte: 42 } }]; //KO
	optional int64 qux = 3 [(validate.rules).int64 = { in: [1, 2, 3] }]; //KO
}
```

**Comment by bjaglin** [comment]
I am not familiar with antlr, but looking at https://github.com/protostuff/protostuff-compiler/blob/61b53fa/protostuff-parser/src/main/antlr4/io/protostuff/compiler/parser/ProtoParser.g4#L210-L235, I think we can see that the text format support is partial:
- support for maps with several attributes lack `,` as a separator
- recursive maps literals are only supported with the colon-less syntax
- arrays are not supported at all

**Comment by jvolkman** [comment]
The whole text format is supported. Text format is not well-specified publicly, but the canonical parser can be found [here](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/text_format.cc), and a distilled grammar can be found [here](https://github.com/jvolkman/intellij-protocol-buffer-editor/blob/master/core/src/main/bnf/textformat.bnf).

In addition, `map` fields in proto generate implicit structures with `key` and `value` fields that can be used in text format. So the following would be valid:

```protobuf
syntax = "proto3";
import "google/protobuf/descriptor.proto";

package foo.bar;

message TestMessage {
  message Option {
    map<string, int32> map = 1;
  }
  extend google.protobuf.FieldOptions {
    Option option = 2000;
  }

  string test_field = 10 [ (option) = {
    map [
      { key: 'foo', value: 1 },
      { key: 'bar', value: 2 }
    ]
  }];
}
```

**Comment by bjaglin** [comment]
Thanks for the context @jvolkman, and interesting to see https://github.com/google/intellij-protocol-buffer-editor, although I understand this is currently for educational purpose.

> The whole text format is supported

You mean that text format is fully supported to express option values in the language? When I said support was partial, I meant the support of text format in the protostuff compiler that is used by this plugin.

> In addition, map fields in proto generate implicit structures with key and value fields

My bad, by "map", I meant the curly brace key/value syntaxt in text format, not the map type from protobuf.

**Comment by jvolkman** [comment]
> You mean that text format is fully supported to express option values in the language? When I said support was partial, I meant the support of text format in the protostuff compiler that is used by this plugin.

Yeah. This part of the proto language isn't well-specified, but `protoc` just defers to the text format parser for these long form options ([relevant code](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/descriptor.cc#L6994) in `descriptor.cc`).

**Comment by nickcaballero-mm** [comment]
+1

**Comment by jvolkman** [comment]
Shameless plug for anyone that needs to use the types of long-form options described in this issue: https://plugins.jetbrains.com/plugin/14004

**Comment by kshchepanovskyi** [comment]
This issue is closed as plugin is not supported anymore. 
Please switch to https://github.com/jvolkman/intellij-protobuf-editor.
