### ISSUE TITLE
Jump to protobuf message definition (in .proto files) from source code

### ISSUE THREAD

**Issue by bybyte** [protostuff/protobuf-jetbrains-plugin#144]
From usages of the generated protobuf classes, is it possible to jump to the message definitions in the .proto files (as opposed to the generated source code)? I should mention that I don't build using CLion -- I use Make from the command line -- and import compile_commands.json to have CLion index the project nonetheless.

I would find it helpful as I rarely need to navigate the actual generated source code, while I want to look at the definitions in the .proto files. Right now, I manually search (CTRL+SHIFT+N) for the correct .proto file (whose name I need to remember).

**Comment by kamalgs** [comment]
This would be a very useful feature to have.  We use protobuf extensively for request / response structures.  Jumping to the protobuf message definition would be very useful while trying to understand structure / types of attributes.

**Comment by kshchepanovskyi** [comment]
This issue is closed as plugin is not supported anymore. 
Please switch to https://github.com/jvolkman/intellij-protobuf-editor.
