### ISSUE TITLE
Plugin is not working in GoLand 2019.1.3

### ISSUE THREAD

**Issue by kagile** [protostuff/protobuf-jetbrains-plugin#145]
**Describe the bug**
Plugin is simply not working in Goland. No syntax highlighting, No auto completion

**To Reproduce**
Just install the latest version.

**Expected behavior**
It must work in GoLand!!

**Screenshots**
![s11](https://user-images.githubusercontent.com/16206875/60716216-69006b00-9f3c-11e9-95a0-a369cdcc115e.png)
![s12](https://user-images.githubusercontent.com/16206875/60716217-69990180-9f3c-11e9-95f4-bdabcaac8ec5.png)

**Plugin (please complete the following information):**
GoLand 2019.1.3
Build #GO-191.7479.32, built on May 30, 2019
Licensed to ******
Subscription is active until September 20, 2019
JRE: 1.8.0_202-release-1483-b53 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-154-generic

**Comment by songxuexian** [comment]
This is working. #134 (comment)
