### ISSUE TITLE
Import cause 'file not found' error

### ISSUE THREAD

**Issue by zredb** [protostuff/protobuf-jetbrains-plugin#146]
**Describe the bug**
I'm using Rider to develop the C# grpc program, when I use import like this:
import "Common.proto";
in another .proto file,
then build the project, I'll receive the file not found error.
![image](https://user-images.githubusercontent.com/8102504/64771918-5af54900-d582-11e9-8ffd-a5ad87e8cffb.png)
when I want to set the 'custom include paths', but when I click the 'Add' button and select a file, the 'text area' display nothing. 
![image](https://user-images.githubusercontent.com/8102504/64772168-baebef80-d582-11e9-8e57-5ac963cb847a.png)

**Plugin (please complete the following information):**
 - OS: [Windows]
 - Plugin version: [ 0.13.0]
 - IDE: [ IntelliJ iDEA 2019.2]

**Comment by kshchepanovskyi** [comment]
This issue is closed as plugin is not supported anymore. 
Please switch to https://github.com/jvolkman/intellij-protobuf-editor.
