### ISSUE TITLE
Plugin doesn't working on WebStorm

### ISSUE THREAD

**Issue by wickedev** [protostuff/protobuf-jetbrains-plugin#148]
**Describe the bug**
Plugin doesn't working on WebStorm

**To Reproduce**
1. `git clone -b grpc https://gitlab.com/wickedev/amki-web`
2. amki-web project open in WebStorm (2019.2.3)
4.  Does not recognize proto file in WebStorm (src/protos/hello.proto)

**Expected behavior**
Syntax highlighting and autocomplete work in WebStorm as well as IntelliJ

**Screenshots**

WebStorm 2019.2.3
![image](https://user-images.githubusercontent.com/5603687/66127546-ea909380-e626-11e9-80a5-ebb0318d4d8f.png)

WebStorm 2019.2.3
![image](https://user-images.githubusercontent.com/5603687/66127565-f3816500-e626-11e9-803c-ae2b0bba6a89.png)

IntelliJ 2019.2.2
![image](https://user-images.githubusercontent.com/5603687/66127647-23306d00-e627-11e9-9ec1-19915b1c14d0.png)

**Plugin (please complete the following information):**
 - OS: Mac
 - Plugin version: 0.13.0
 - IDE: WebStorm 2019.2.3

**Additional context**
React Project

Thanks for your efforts

**Comment by kshchepanovskyi** [comment]
This issue is closed as plugin is not supported anymore. 
Please switch to https://github.com/jvolkman/intellij-protobuf-editor.
