### ISSUE TITLE
Applying multiple field options (or using commas) gets marked as a syntax error

### ISSUE THREAD

**Issue by LethiferousMoose** [protostuff/protobuf-jetbrains-plugin#149]
**Describe the bug**
I began noticing this most frequently when using the third-party plugin [protoc-gen-validate](https://github.com/envoyproxy/protoc-gen-validate). This plugin has multiple field options, that can be applied in sequence as well as lists such as "in" and "not_in". These are all valid proto syntax and compile and generate normally, but the plugin marks them as issues once a comma is present.

**To Reproduce**
1. Install protoc-gen-validate plugin in a project (or create options that can be applied with commas)
2. Apply field options that contain comments
4. See red underlines

**Expected behavior**
Red underlines will not be present for valid syntax

**Screenshots**
![image](https://user-images.githubusercontent.com/24547864/69171779-348fe480-0ac2-11ea-8851-af70d973f287.png)

**Plugin (please complete the following information):**
 - OS: Windows 10
 - Plugin version: 0.13.0
 - IDE: e.g. IntelliJ iDEA 2019.1.3 (Ultimate Edition)

**Comment by jvolkman** [comment]
#143 has some discussion on this.

**Comment by LethiferousMoose** [comment]
Thanks, I will just close my issue since it is the same.
