### ISSUE TITLE
.proto files are not getting identified  

### ISSUE THREAD

**Issue by vineethvnair0** [protostuff/protobuf-jetbrains-plugin#150]
**Describe the bug**
I have installed  protobuff, and I have added my proto folder to source  as mentioned in 
https://github.com/protostuff/protobuf-jetbrains-plugin(tried both method 1 and 3). But my .proto files are not getting identified. My proto folder is kept outside the src folder, also moving it inside the resource folder doesn't help.

**To Reproduce**
1. Install proto support 
2. Restart IDE
3. File contents are like normal txt file.

**Expected behavior**
Expected the proto syntax highlights.  Also syntax corrections.

**Screenshots**
![image](https://user-images.githubusercontent.com/13416977/71076601-02020600-21ac-11ea-9ced-df855c3a8ce8.png)

**Plugin (please complete the following information):**
 - OS: Mac os 10.14.6
 - Plugin version: 0.13.0
 - IDE: 2018.3.3

**Comment by wpxun** [comment]
same problem for me，windows10 system，Plugin version: 0.13.0

**Comment by NGLSL** [comment]
I have the same problem

**Comment by qiujiancn** [comment]
me too, have the same problem.

**Comment by rksilvergreen** [comment]
Same problem

**Comment by kshchepanovskyi** [comment]
This issue is closed as plugin is not supported anymore. 
Please switch to https://github.com/jvolkman/intellij-protobuf-editor.
