### ISSUE TITLE
proto-3 'options' syntax is not fully supported

### ISSUE THREAD

**Issue by axb** [protostuff/protobuf-jetbrains-plugin#151]
**Describe the bug**
options syntax (https://developers.google.com/protocol-buffers/docs/proto3#options) on methods is not parsed correctly

**To Reproduce**
Example - perfectly valid option definition on rpc, which is considered invalid by the plugin

 rpc CreateOrder (Order) returns (Order) {
        // sample ACL
        option (private.authz.rpc_acl) = {
            acl: {
                role_id: PF_SYSADMIN
                action_permissions: A
                data_permissions: ANY
            }
            acl: {
                role_id: A_MNGR
                action_permissions: A
                action_permissions: E
                data_permissions: SELF
                data_permissions: ACCOUNT
            }
        };
    };

**Expected behavior**
The syntax is parsed and hilighted adequately. Code formatting works as expected.

**Screenshots**

**Plugin (please complete the following information):**
 - OS: Mac
 - Plugin version: 0.13.0
 - IDE:  IntelliJ iDEA 2019.3.1

**Additional context**

**Comment by kgignatyev** [comment]
same behavior in IJ 2019.3.2 , syntax is not highlighted properly, but click trough navigation works (command click of parameter navigates to its definition)

**Comment by ArieDeha** [comment]
I don't know what make this happen, at first when using proto3, the syntax highlighter etc is down, but when I change the syntax to:
`syntax = "proto2"`
the syntax highlighter suddenly turn back on, with some errors from the proto3 to proto2 changes...

So I change back to:
`syntax = "proto3"`
Every syntax highlighter, ctrl click for code navigation, etc finally up again.

I just think that I need to report this, just in case anybody need more info.

GoLand 2019.3.2
Windows 10
Plugin ver.: 0.13.0
![image](https://user-images.githubusercontent.com/9045281/74595431-c385ac00-5073-11ea-816a-99a153b0ce95.png)

**Comment by kshchepanovskyi** [comment]
This issue is closed as plugin is not supported anymore. 
Please switch to https://github.com/jvolkman/intellij-protobuf-editor.
