### ISSUE TITLE
Top level options with message fields incorrectly report syntax errors

### ISSUE THREAD

**Issue by eliaperantoni** [protostuff/protobuf-jetbrains-plugin#152]
**Describe the bug**
A top level `option` statement of message type, that has a nested message field, will report various errors, depending on how you place semicolons. 
This happens even though the protobuf compiler is able to compile.

**To Reproduce**
1. Clone this repo https://github.com/grpc-ecosystem/grpc-gateway
2. Add import paths for the repo root folder and the `third_party/googleapis` subdirectory
3. Create a protobuf file with this content:
```protobuf
syntax = "proto3";
package proto;

import "protoc-gen-swagger/options/annotations.proto";

option (grpc.gateway.protoc_gen_swagger.options.openapiv2_swagger) = {
    info: {
        title: "MySite";
        description: "MySite REST API";
        version: "x.y.z";
    };
    host: "mysite";
    base_path: "/grpc";
};
```

**Expected behavior**
No errors reported as the file can compile just fine (protobuf.js also works)

**Screenshots**
![bug](https://user-images.githubusercontent.com/6002855/75243018-73bc8880-57c9-11ea-9d7e-4934bdbe14dc.png)

**Plugin (please complete the following information):**
 - OS: Manjaro x64
 - Plugin version: 0.13.0
 - IDE: GoLand 2019.3.2

**Additional context**
I found out that this
```protobuf
option (grpc.gateway.protoc_gen_swagger.options.openapiv2_swagger) = {
    host: "onocontroller:7576"
    base_path: "/grpc"
};
option (grpc.gateway.protoc_gen_swagger.options.openapiv2_swagger).info = {
    title: "ONO"
    description: "ONO Lean Logistics REST API"
    version: "x.y.z"
};
```
has the same effect but does not trigger any syntax error.

**Comment by jvolkman** [comment]
Same as #143.

**Comment by eliaperantoni** [comment]
Sorry, tried searching but didn't found anything similar :/
