### ISSUE TITLE
Unable to open protobuf file

### ISSUE THREAD

**Issue by christian-storm** [protostuff/protobuf-jetbrains-plugin#21]
I'm using the latest release protobuf plugin and pycharm CE:

The error in the eventlog is:
1:12:17 PM NoClassDefFoundError: com/intellij/psi/impl/source/resolve/reference/impl/providers/FilePathReferenceProvider

**Comment by kshchepanovskyi** [comment]
Thank you for report, I will fix it as soon as possible.

**Comment by kshchepanovskyi** [comment]
UPD: All JetBrains products except IntelliJ IDEA and Android Studio are affected.

**Comment by kshchepanovskyi** [comment]
Fixed: https://github.com/protostuff/protobuf-jetbrains-plugin/releases/tag/v0.4.1

It should become available in JetBrains plugin repository in a couple of hours.

**Comment by kshchepanovskyi** [comment]
Now you can update plugin from repository (run "Help -> Check For Updates...").

**Comment by christian-storm** [comment]
Fixed!  Thank you for the quick turnaround.
