### ISSUE TITLE
Allow protobuf compilation

### ISSUE THREAD

**Issue by mkilpatrick** [protostuff/protobuf-jetbrains-plugin#29]
It would be great if the protobufs could be compiled through IntelliJ with a source output that is configurable. I saw a response to someone's comment on [this](https://plugins.jetbrains.com/plugin/8277?pr=androidstudio&ec=true&offset=0&max=15) page saying that this most likely won't be implemented and to use protoc with your build tool.

While I understand using protoc for protobuf compiling, it makes using IntelliJ less convenient. I can either compile all of my source code with my own [custom] build tool outside of IntelliJ, or I can use IntelliJ for compilation while developing. Compiling everything through IntelliJ makes development much easier and more seamless. Of course, the plugin could simply call protoc behind the scenes, much like other protobuf plugins do.

**Comment by kshchepanovskyi** [comment]
I agree that source code generation from IntelliJ IDEA by triggering protoc might be convenient. If we talk about IDEA-based project that do not use external build system like maven/gradle, then it will be not only convenient, but also mandatory.

Generating source code from proto files as a part of compilation is not a priority for me now (all my projects use maven or gradle), so I will consider implementing it only when I finish with release 1.0 - https://github.com/protostuff/protobuf-jetbrains-plugin/wiki/Roadmap.

However, if somebody is willing to help - I will gladly accept a pull requests for this feature and make a new public release as soon as it is ready.

**Comment by kshchepanovskyi** [comment]
> the plugin could simply call protoc behind the scenes, much like other protobuf plugins do.

There is only one "other" plugin, and its functionality is very limited - as far as I remember, it can generate only java code, and it does not allow to use any additional `protoc` plugins or options.

If we are going to add this feature, it should be much more flexible:

1. Allow code generation for all languages supported by the latest `protoc`.
2. Do no force user to install `protoc` on a machine, it can be bundled together with plugin (but allow to use external one as well).
3. Allow external `protoc` plugins, like [gRPC Java Codegen Plugin for Protobuf Compiler](https://github.com/grpc/grpc-java/tree/master/compiler).
4. Output directory should be configurable.
5. If output directory is not configured, it should be selected automatically depending on IDE and project type. Generated code should be added to the project sources, if applicable.

**Comment by sivasankariit** [comment]
It would be very useful if the compile functionality supports custom include paths for proto files for each submodule in a project. Please see https://github.com/nnmatveev/idea-plugin-protobuf/commit/ab1497422b68f0aa350e1db7c4c8266032c35053 for similar functionality in the other protobuf plugin.

**Comment by dingzhenke** [comment]
I have the same question，has this question been settled yet？

**Comment by kshchepanovskyi** [comment]
Currently I do not know when I will have time to start working on it.
But if there is somebody willing to help, I will gladly accept pull request.

**Comment by hsestupin** [comment]
Hi,

I hope I will have some time in the near future to add initial support for protobuf compilation. But I believe that it's better to start with just a minimal implementation to simply allow users to add protobuf compilation to their projects. In my opinion having this option would be enough for 90% of use cases.
How do you think is it acceptable to not implement every desired feature at the start? 

> Do no force user to install protoc on a machine, it can be bundled together with plugin (but allow to use external one as well).

I don't think it's a good idea because anyway every project should have the opportunity being built  from console that means user will definitely have **protoc** already installed. In my opinion this feature will also add complexity and ambiguity because **protoc** version from console should be the same as the **protoc** version bundled with the plugin. What do you think?

**Comment by Stranger2015** [comment]
As I figured out nothing makes you to write protoc as the whole. It's enough to write the plugn(s)

**Comment by kshchepanovskyi** [comment]
@hsestupin 

> I believe that it's better to start with just a minimal implementation to simply allow users to add protobuf compilation to their projects. In my opinion having this option would be enough for 90% of use cases. How do you think is it acceptable to not implement every desired feature at the start?

Sure, that makes sense.

> > Do no force user to install protoc on a machine, it can be bundled together with plugin (but allow to use external one as well).

> I don't think it's a good idea because anyway every project should have the opportunity being built from console that means user will definitely have protoc already installed. In my opinion this feature will also add complexity and ambiguity because protoc version from console should be the same as the protoc version bundled with the plugin. What do you think?

In the same manner I assumed that every project has a build system like ant/maven/whatever once. But there are lots of people who don't use that stuff and want IDE to compile and build code.

However, you are right - it will add complexity and ambiguity. So it is better to start without it.

**Comment by kshchepanovskyi** [comment]
This issue is closed as plugin is not supported anymore. 
Please switch to https://github.com/jvolkman/intellij-protobuf-editor.
