### ISSUE TITLE
Imports are not working in WebStorm 2016.3 for "Resource Roots"

### ISSUE THREAD

**Issue by daoquangphuong** [protostuff/protobuf-jetbrains-plugin#30]
i can't reference "message" if it's in an import file

**Comment by kshchepanovskyi** [comment]
Hi, imports are fully supported. 

Please make sure that folder where the file you are importing is located is marked as a "sources root", and you are using relative path against source root in the import statement.

**Comment by daoquangphuong** [comment]
Hi, i marked "Root" as a "sources root" but still doesn't work
```
Root
  |--pb
        |--A.proto
        |--B.proto
```
in A.proto file
```
syntax = "proto3";
package pb;
import "pb/B.proto";
...
```

**Comment by kshchepanovskyi** [comment]
Ok, then I need more information:

1. What IDE are you using, what version?
2. Can you please upload project that reproduces an issue to github (please include all files).
3. Also a screenshot with open project structure and file with import statement can be useful.

**Comment by daoquangphuong** [comment]
Hi. please check this and ask me what you need
1. WebStorm 2016.3.1 and Protobuf Support v 0.7.0
2. For some reasons i can't public my project. but i created a simple project for testing
[protoTest.zip](https://github.com/protostuff/protobuf-jetbrains-plugin/files/773552/protoTest.zip)

3. Screenshots
<img width="1388" alt="screen shot 2017-02-14 at 15 46 14" src="https://cloud.githubusercontent.com/assets/14815108/22921752/7e864b8e-f2cd-11e6-84f6-7d0f4c54a2b3.png">
<img width="1149" alt="screen shot 2017-02-14 at 15 50 14" src="https://cloud.githubusercontent.com/assets/14815108/22921767/8f6d1bda-f2cd-11e6-846d-5b44782a113e.png">

**Comment by kshchepanovskyi** [comment]
Thank you for reporting this, it is indeed a defect. I will try to fix it soon.

**Comment by kshchepanovskyi** [comment]
**Update**: in WebStorm, imports are not working if you mark directory as "resource root". However, it should work as expected if you mark directory as "Test Sources Root".

Alternatively you can use "Custom Include Paths" feature, added in the [release 0.5.0](https://github.com/protostuff/protobuf-jetbrains-plugin/releases/tag/v0.5.0).

**Comment by kshchepanovskyi** [comment]
https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000163684-Resource-roots-in-WebStorm
