### ISSUE TITLE
Have not support 'keyword' for 'singular'

### ISSUE THREAD

**Issue by huangpeng1126** [protostuff/protobuf-jetbrains-plugin#35]
I found the keyword 'singular' is not recognized by the plugin. 

I use version 0.7

**Comment by kshchepanovskyi** [comment]
Interesting.
Is it a new keyword? Can you please add some example with it?

**Comment by kshchepanovskyi** [comment]
According to spec, there is no such keyword nor in proto2 nor in proto3:

- https://developers.google.com/protocol-buffers/docs/reference/proto2-spec
- https://developers.google.com/protocol-buffers/docs/reference/proto3-spec
