### ISSUE TITLE
Icons size cause misalignment in new PHPStorm

### ISSUE THREAD

**Issue by malarzm** [protostuff/protobuf-jetbrains-plugin#36]
JetBrains told me it's 3rd party issue so here I am :) For what it's worth it seems like icon size has changed with PHPStorm 2017.1 (I'd assume it's for all their new stuff). Original report is here https://youtrack.jetbrains.com/issue/WI-35626 

![image](https://cloud.githubusercontent.com/assets/4040120/24357997/4867f402-1308-11e7-9fce-99b9b99c9425.png)

**Comment by kshchepanovskyi** [comment]
Thank you for reporting this, I will take a look.

**Comment by kshchepanovskyi** [comment]
Fixed, will added to next release.

**Comment by malarzm** [comment]
Thanks @kshchepanovskyi!

**Comment by kshchepanovskyi** [comment]
New icon should also be a better fit into a new IntelliJ IDEA design.

| Old  | New |
|--------|---------|
|![](https://github.com/protostuff/protobuf-jetbrains-plugin/raw/e3c81fbeed3b3f86eef7f6550845617973202a9b/src/main/resources/io/protostuff/protobuf-jetbrains-plugin/icons/proto%402x.png) | ![](https://github.com/protostuff/protobuf-jetbrains-plugin/raw/18a7341c27762c16a5a333b451ffbf7e67a9763f/src/main/resources/io/protostuff/protobuf-jetbrains-plugin/icons/proto%402x.png) |
