### ISSUE TITLE
proto2/proto3 syntax validation

### ISSUE THREAD

**Issue by mdelambilly** [protostuff/protobuf-jetbrains-plugin#39]
It seems syntax keyword is not used for validation process. when I use it and set it to "proto3", I can still use label optional or required without raising any validation error. In the same way, when I put it to "proto2" empty label is allowed.

It would be great to have it to quickly see what is wrong when we convert proto2 files to proto3 !

**Comment by kshchepanovskyi** [comment]
It's little bit bigger than just file modifiers.
Also it includes:
- default values are not supported in proto3
- groups are not supported in proto3
- enums must contain a constant with value = 0, and it should be first value in the list

But also there are good news - all these checks are relatively straightforward and can be easily implemented by adding new checks to https://github.com/protostuff/protobuf-jetbrains-plugin/blob/master/src/main/java/io/protostuff/jetbrains/plugin/annotator/ProtoErrorsAnnotator.java

I would gladly accept a pull request for this feature (or a part of it).
