### ISSUE TITLE
Error message for field modifier inside oneof block

### ISSUE THREAD

**Issue by cconroy** [protostuff/protobuf-jetbrains-plugin#49]
When I use a `oneof` with this plugin, it reports a syntax error on the last field.

e.g.

```
message Foo {
  oneof bar {
    optional string baz = 1;
    optional int32 fizz = 2;
  }
}
```

It reports: "extraneous input fizz, expecting '='"

Plugin version 0.8

see: https://developers.google.com/protocol-buffers/docs/reference/java-generated#oneof-fields

**Comment by kshchepanovskyi** [comment]
You cannot use `optional`, `required` or `repeated` field modifiers inside of an `oneof` block.
The only thing to improve here is error message.

**Comment by cconroy** [comment]
Doh! Good call. Thanks!
