### ISSUE TITLE
Code completion support

### ISSUE THREAD

**Issue by orlabdev** [protostuff/protobuf-jetbrains-plugin#51]
Dear IntelliJ/Webstorm/Gogland experts, I am new to these IDE(s). I am working on some research module with gRPC, Go and NodeJS. I have chosen Idea for its maturity in terms of development. But, I have been beating my head to get the code suggestion working for the protobuf-plugin and protobuf code. I have used the Google Protobuf-dt plugin in eclipse and the code suggestion is working fine with that plugin in eclipse but, not with the Idea protobuf-plugin 0.8.0. Can anyone help or suggest on this feature please. Lots of thanks in advance.
 

Best regards ..

**Comment by kshchepanovskyi** [comment]
That's one of the next things I'm planning to implement (probably by the end of summer).

**Comment by hmemcpy** [comment]
Hi, any news about this? If not, perhaps I could try to contribute some CompletionContributors to add at least some basic completion support?

**Comment by kshchepanovskyi** [comment]
Sure, why not.

Based on my current workload I can say that I do not have time to work on it in January, so I would greatly appreciate any help.

@kaathewise already added some indexes that can be used for code completion in https://github.com/protostuff/protobuf-jetbrains-plugin/pull/78

**Comment by eaglo** [comment]
any news on code completion support? its a great plugin so far but having no code completion for proto messages is bugging me for a while now :(

**Comment by kshchepanovskyi** [comment]
Started working on it week ago :)

**Comment by kshchepanovskyi** [comment]
Hi, sorry, but there are no news yet. I started working on it couple of month ago, but it's more challenging to implement it than I expected. Most likely I will resume working on it after new year.

**Comment by wqhyw** [comment]
How's it going?

**Comment by advra** [comment]
Hello, any updates on this feature?

**Comment by yossefaz** [comment]
Hello there : any update ?

**Comment by kshchepanovskyi** [comment]
This issue is closed as plugin is not supported anymore. 
Please switch to https://github.com/jvolkman/intellij-protobuf-editor.
