### ISSUE TITLE
Message could be collapsible

### ISSUE THREAD

**Issue by Veske** [protostuff/protobuf-jetbrains-plugin#52]
IntelliJ provides a way of collapsing methods so that a develop can view only whats needed if a file is big.
This could be very useful feature in this plugin also so that developers can collapse messages for instance.

Here is an image that shows how it looks for methods in IntelliJ for Java. The darker button can be clicked and the method will be collapsed.
![collapse](https://user-images.githubusercontent.com/5602603/27085624-82eb9b00-5058-11e7-906a-2f1a3e202c5e.png)

**Comment by kshchepanovskyi** [comment]
Preview:

![image](https://user-images.githubusercontent.com/4040120/27754302-8fbdff1a-5df2-11e7-8ece-77cadd3099ee.png)
