### ISSUE TITLE
No syntax highlighting under IDEA 2017.2

### ISSUE THREAD

**Issue by alexander-yevsyukov** [protostuff/protobuf-jetbrains-plugin#70]
I've tried to install the plug-in `v0.10.1` after IDEA's prompt. It did install, but there's no syntax highlighting and other features.

The plugin does appear under Plugins in Preferences. Removing and installing back did not help. I've also tried to install `v0.9.0` from disk. But the result is the same.

I used to have custom type for `.proto` files. But I double check-ed: it's now removed. There are no other plugins for `.proto` files.

My environment:
 * macOS Sierra (v10.12.5)
 * IntelliJ IDEA 2017.2

Please assist.

**Comment by alexander-yevsyukov** [comment]
I also did “Invalidate Cache / Restart” in idea — no luck.

**Comment by kshchepanovskyi** [comment]
Actually it is quite hard to guess what might be wrong.
Please check if file type is registered correctly:
![image](https://user-images.githubusercontent.com/4040120/28539437-5163d070-70ba-11e7-99d1-4f7ff9d0d997.png)

As last resort I can suggest to clean IDEA settings folder and install plugin again.

**Comment by alexander-yevsyukov** [comment]
There was `Protobuf` item, but there was no associated pattern. After I added it, the plug-in started working. Thanks for your help!

**Comment by shuiyibu** [comment]
Thanks!

> Actually it is quite hard to guess what might be wrong.
> Please check if file type is registered correctly:
> ![image](https://user-images.githubusercontent.com/4040120/28539437-5163d070-70ba-11e7-99d1-4f7ff9d0d997.png)
> 
> As last resort I can suggest to clean IDEA settings folder and install plugin again.
