### ISSUE TITLE
proto3 extensions for options should be supported

### ISSUE THREAD

**Issue by edthorne** [protostuff/protobuf-jetbrains-plugin#71]
While proto3 replaces regular extensions with [Any](https://developers.google.com/protocol-buffers/docs/proto3#any), [custom options](https://developers.google.com/protocol-buffers/docs/proto3#custom_options) are a valid use for the extension mechanism.

From the proto3 Language Guide:
> Note that creating custom options uses extensions, which are permitted only for custom options in proto3.

**Comment by kshchepanovskyi** [comment]
Thank you for reporting this, I also noticed that in some of `protoc`-s test files.
It will be fixed in the next release.
