### ISSUE TITLE
Add a setting to support different file extensions e.g. *.protodata

### ISSUE THREAD

**Issue by zchen24** [protostuff/protobuf-jetbrains-plugin#80]

**Comment by kshchepanovskyi** [comment]
It is already supported by IDE out of the box:

![image](https://user-images.githubusercontent.com/4040120/30267800-5f0d8e20-96ec-11e7-8c2c-5ae9aa407de6.png)

You can add more extensions in `Settings -> Editor -> File Types -> Protobuf`.
