### ISSUE TITLE
import files in same folder failed

### ISSUE THREAD

**Issue by ljmsc** [protostuff/protobuf-jetbrains-plugin#81]
when i have two different .proto files in the same folder and want to import one of them in the other the syntax is like this:
```import "MyOtherFile.proto"```
the files are correctly generated with the ``protoc`` command but the editor shows an error "File not found"
When i import it like this:
```import "foldername/MyOtherFile.proto"```
the editor shows no more errors but the compiler fails. I guess this is an error in the syntax parser.

**Comment by atanasbozhkov** [comment]
I have the same issue.

**Comment by kshchepanovskyi** [comment]
Check package statement, it should conform to the folder structure.

https://github.com/protostuff/protobuf-jetbrains-plugin/issues/68#issuecomment-316376566

**Comment by atanasbozhkov** [comment]
@kshchepanovskyi thanks for the insight. Removing the package definition from the proto does indeed work. 
While the fault was in my project structure it's not immediately clear why that it happening from the error messages. 

Should we consider adding support for detecting whether the package structure is different from the one defined on the proto and show a more useful error?

**Comment by kshchepanovskyi** [comment]
Yes, you are right. Probably a warning should be added if a file's location does not match package.

Created https://github.com/protostuff/protobuf-jetbrains-plugin/issues/82
