### ISSUE TITLE
Syntax proto3 import and meta tags not recognized

### ISSUE THREAD

**Issue by jorgjanke** [protostuff/protobuf-jetbrains-plugin#83]
Thanks for the plugin!
Previously, imports and meta were properly recognized.  This was lost recently.
Intellij 2017.2.4 (ultimate) - v0.10.2

1) import
2) message meta info
3) field meta info
4) use of imports

![image](https://user-images.githubusercontent.com/168846/31064418-d321b944-a6f0-11e7-8da7-f9d2ffc7e5d1.png)

**Comment by kshchepanovskyi** [comment]
Hi,

I think it's related to https://github.com/protostuff/protobuf-jetbrains-plugin/issues/81

Please check imports & package statements in proto files, they should correspond to the folder structure.

**Comment by jorgjanke** [comment]
Thanks - all files are actually all in the same directory.
Nevertheless - in > Preferences > Protobuf Support
I added the specific project directory. After that, it worked.

I think that it should not be necessary to hardcode the directory, especially as the protoc compiler works fine.
Hardcoding the directory also has the issue that different projects may have the same file names and with the hardcoded directories there might be unexpected results.
So, it should only use the Preference directories, if there is nothing found in the same direcory as the file is in.

**Comment by kshchepanovskyi** [comment]
Can you please describe how you run `protoc`, from which directory and what is `-I` option?

**Comment by jorgjanke** [comment]
cd protoDirectory
protoc --java_out=./javaDirectory source1.proto source2.proto ....
i.e. no use of --proto_path (was not aware of that before this ;-)

The --proto_path can be used multiple times ... i.e. similar to the directories in Preferences > Protobuf Support.
I can lie with the restriction that you have to hardcode your directories and in my case the names of the different proto files are different - with one exception (meta.ptoto), but that file is copied anyway to the different projects, so it does not matter which is picked up.

Nevertheless, checking the local directory first, would be great.

**Comment by kshchepanovskyi** [comment]
Ok, basically it works with `protoc` for you because current directory where you run it is a default "include path".
In case of IDEA plugin, it's a little bit tricky to recognize where such "default include path" directory is (unless it is explicitly marked as source root).
I'll think about adding few more heuristics in order to detect include paths in a better way.

**Comment by bhechinger** [comment]
Any updates on this? As of today it still has this issue. :(

**Comment by kshchepanovskyi** [comment]
Sorry,  I'm having problems with spare time last ~ half year. However, I hope that soon I will be able to make this fix.

**Comment by Emixam23** [comment]
Hey !

My Goland IDE on Mac doesn't understand -> `syntax = "proto3"` do you know why?

**Comment by kshchepanovskyi** [comment]
@Emixam23 what plugin are you using? If you are sure it's a defect in the plugin, please create separate issue for it and add some screenshots.

**Comment by Emixam23** [comment]
Hey,

I don't know I felt like it was linked :/

**Build #GO-182.3911.47, built on August 9, 2018**
<img width="574" alt="screen shot 2018-08-20 at 18 36 50" src="https://user-images.githubusercontent.com/6987848/44370521-86555380-a4a8-11e8-982f-b9ee44075378.png">

**protobuf 0.10.2**
<img width="1053" alt="screen shot 2018-08-20 at 18 37 09" src="https://user-images.githubusercontent.com/6987848/44370540-98cf8d00-a4a8-11e8-9bc1-f55c2d6b6a76.png">

**package expected, got syntax**
<img width="194" alt="screen shot 2018-08-20 at 18 37 50" src="https://user-images.githubusercontent.com/6987848/44370593-e3510980-a4a8-11e8-8c2d-c8b5003f869c.png">

*Either I put the *syntax* before or after the package declaration, it doesn't change nothing...*

Max,

**Comment by Emixam23** [comment]
Hey !

I just found out why when I was creating a file "example.proto" it was recognized as go file or text file, and then the syntax was showing errors..

**Solution**

- Close Goland
- Remove the .idea folder -> `rm -rf .idea`
- reopen the project with Goland

Hope it helps !

Max
