### ISSUE TITLE
Import of google/protobuf/empty.proto results in file not found error

### ISSUE THREAD

**Issue by maguro** [protostuff/protobuf-jetbrains-plugin#86]
Since there is no physical path to `google/protobuf/empty.proto` the import of `google/protobuf/empty.proto` results in a file not found error.  It would be handy if one could specify an import path of `github.com/golang/protobuf` and have the proto files' `package` declaration dictate their import paths.

Here, the package declaration found in `github.com/golang/protobuf/ptypes/empty/empty.proto` is

    package google.protobuf;

This would result in `empty.proto` being available via the import path `google/protobuf/empty.proto`.

An alternative is specifying the proto version and/or its HOME and have these "built-in" imports available.

**Comment by nornagon** [comment]
I'm also seeing this issue (but in a Java project, so github.com/golang/protobuf wouldn't be the right package to import)

**Comment by kshchepanovskyi** [comment]
While it is not published yet, you may try https://jenkins.ksprojects.org/job/protostuff/job/protobuf-jetbrains-plugin/job/master/6/artifact/build/distributions/protobuf-jetbrains-plugin-0.10.2.zip - I would appreciate any feedback.
