### ISSUE TITLE
[feature request] set global protobuf path

### ISSUE THREAD

**Issue by llvim** [protostuff/protobuf-jetbrains-plugin#88]
I am using protobuf and tensorflow serving a lot, a log of my project need set include path,

Is there any plan to set global include path?

**Comment by kshchepanovskyi** [comment]
Can you please what do you mean by "global"? 
There is already project-specific setting - named "custom include path", check here - https://github.com/protostuff/protobuf-jetbrains-plugin/releases/tag/v0.5.0

**Comment by biolee** [comment]
Now a lots project include `protobuf, protobuf-go, gogo, tensorflow`, I need to add them manually every time.

if I do not open a project, the `custom include path` is not settable.

![screenshot](https://user-images.githubusercontent.com/7426917/33297731-9a98a4e8-d41d-11e7-8303-3e581c62a763.png)

`custom include path` is `project-specific setting`, `global` is not `project-specific setting`, it is default for every project, intellij's gopath setting mechanism inspire me for this feature request.

![screenshot](https://user-images.githubusercontent.com/7426917/33297996-e0fe281c-d41e-11e7-9999-7f0dd12b94d5.png)

**Comment by kshchepanovskyi** [comment]
Thank you, it totally makes sense now. It should not be very complicated to implement, so I will try to add it to next release.

**Comment by biolee** [comment]
is there anyone working on this?

**Comment by kshchepanovskyi** [comment]
I still hope I can find time to fix all issues raised in last half year.
However, I will gladly accept any pull requests with fixes and new features :)

How can I help you?
