### ISSUE TITLE
Support region command to fold code

### ISSUE THREAD

**Issue by wenerme** [protostuff/protobuf-jetbrains-plugin#89]
protobuf plugin will not detect region/endregion comment, I expect I can fold the region/endregion code.

**Comment by kshchepanovskyi** [comment]
Can you please add more details, some examples.

**Comment by wenerme** [comment]
Language support region will show fold icon on region/endregion
![image](https://user-images.githubusercontent.com/1777211/33881446-c42cd7fe-df6f-11e7-87f4-6187cfc4f60f.png)

![image](https://user-images.githubusercontent.com/1777211/33881579-28ac75cc-df70-11e7-9dd9-b69bb0e05772.png)


protobuf don't support region/endregion, fold on region only fold the comment
![image](https://user-images.githubusercontent.com/1777211/33881494-e549520a-df6f-11e7-857c-9c73a6031e1c.png)

![image](https://user-images.githubusercontent.com/1777211/33881598-38c891fc-df70-11e7-8fce-b5b35504be39.png)

**Comment by kshchepanovskyi** [comment]
Thank you for additional info, I'll consider this for one of next releases.
