### ISSUE TITLE
Showing "File not find" in Clion while import protobuf files

### ISSUE THREAD

**Issue by wangzitian** [protostuff/protobuf-jetbrains-plugin#93]
My `Mark forlder as.` only have two options: 'excluded' and 'library files', and I have tried add path in 'Other Settings > Protobuf Support' as the README. However, it is still not working.
My Clion version is 2017.03.03 and using bazel to build.

Should I provide more informations?

Thank you!

**Comment by kshchepanovskyi** [comment]
Adding folder to include path in 'Other Settings > Protobuf Support' should definitely work.

Please create small project that reproduces an issue and attach zipped folder here, I can take a look if that's plugin issue.

**Comment by wangzitian** [comment]
Hi, Kostiantyn,
Thanks for your reaching out! I have located the reason, due to it can not resolve sub-directory.
For example:
proto/
---module_a/
------/a.proto
---module_b/
------/b.proto

a.proto:
package a;

b.proto:
package b;
import "a.proto"

I could solve it by add all the path: ['proto/', 'proto/module_a/', 'proto/module_b/'], as I former only added one path 'proto/'.

**Comment by kshchepanovskyi** [comment]
Cool, I'm closing the issue in this case.
