### ISSUE TITLE
Scroll from Source does not work for .proto files

### ISSUE THREAD

**Issue by aspotashev** [protostuff/protobuf-jetbrains-plugin#94]
Clicking on the "Scroll from Source" button in Project panel does nothing when the plugin is installed and a .proto file is currently opened in the active editor tab.

**Comment by kshchepanovskyi** [comment]
Interesting. It works for me in IntelliJ IDEA 2017.3 on Windows, plugin version 0.10.2.

Can you provide more information? Ideally some small project that reproduces an issue, IDE name and version, operating system name and version.

**Comment by aspotashev** [comment]
It works now, sorry. Must have been a bug in the JetBrains platform that sorted out somehow by now.
