### ISSUE TITLE
protobuf code introspection does not work with python 3.6.4

### ISSUE THREAD

**Issue by pjm4github** [protostuff/protobuf-jetbrains-plugin#95]
I have a proto file that I've compiled for both proto3 and proto2 and run against python 2.7 and python 3.6

When I run my test code Python 3 in the debugger I no longer get any of the required or optional fields in the Variables introspection pane. In addition none of the code-hinting/ autocomplete works at the debug prompt. 

When I run in Python 2 it works. 
The IDE screenshots are shown for both python 2 and python 3

Here's the proto file **addressbook.proto**

```proto
syntax = "proto2";

package tutorial;

message Person {
  required string name = 1;
  required int32 id = 2;
  optional string email = 3;

  enum PhoneType {
    MOBILE = 0;
    HOME = 1;
    WORK = 2;
  }

  message PhoneNumber {
    required string number = 1;
    optional PhoneType type = 2 [default = HOME];
  }

  repeated PhoneNumber phones = 4;
}

message AddressBook {
  repeated Person people = 1;
}

```
Here's the test file **test_addressbook.py**
```py
import addressbook_pb2
person = addressbook_pb2.Person()
person.id = 1234
person.name = "John Doe"
person.email = "jdoe@example.com"
phone = person.phones.add()
phone.number = "555-4321"
phone.type = addressbook_pb2.Person.HOME
print(person)
person2 = addressbook_pb2.Person()
pass
```
**Passing**
Note that the code-hinting shows the email field in Python 2.7 as expected
![pycharm_py2_7_ok](https://user-images.githubusercontent.com/3688079/37546872-42f652f8-2945-11e8-8dfb-37600d9c1c57.png)
**Failing**
Note that the code-hinting does not show the email field in Python 3.6...
![pycharm_py3_6_bad](https://user-images.githubusercontent.com/3688079/37546876-461bb48c-2945-11e8-969e-4d23939017e7.png)

**Comment by kshchepanovskyi** [comment]
Sorry, but problem you described is not related to Protobuf Support plugin. 
This plugin adds some support (highlighting, syntax checks, etc) when you edit `.proto` files. 
You described that there is an issue with python code, which is basically supported by other plugins (and PyCharm itself).

**Comment by kshchepanovskyi** [comment]
Closed as unrelated.
