### ISSUE TITLE
Incorrect working with import keyword

### ISSUE THREAD

**Issue by Sabrak** [protostuff/protobuf-jetbrains-plugin#97]
So.
I have two files in proto folder, A.proto and B.proto. If in B.proto I add **import "A.proto"** the plugin will show error 'File not found'. But protoc works file. Otherwise if I add **import "proto/A.proto"** plugin will work fine but protoc will say:
> protoc: stdout: . stderr: proto/A.proto: File not found.

**Comment by P-A-R-U-S** [comment]
Yes, the issue are still exist. I'm using following version of plugin with Goland IDE 2018.
<img width="766" alt="screen shot 2018-04-10 at 11 56 45 pm" src="https://user-images.githubusercontent.com/1575452/38597043-de4fb562-3d1a-11e8-8411-c2acc17d40a2.png">

**Comment by P-A-R-U-S** [comment]
<img width="1097" alt="screen shot 2018-04-11 at 12 24 45 pm" src="https://user-images.githubusercontent.com/1575452/38632809-6e1291e8-3d83-11e8-8ae9-4b5b9c60fcd0.png">

**Comment by P-A-R-U-S** [comment]
Look like issue related to package keyword. When I add "package" name the "import" does not works properly.
<img width="895" alt="screen shot 2018-04-14 at 12 10 47 am" src="https://user-images.githubusercontent.com/1575452/38764640-8e9726f8-3f78-11e8-9341-fa61f39f3865.png">
<img width="927" alt="screen shot 2018-04-14 at 12 11 01 am" src="https://user-images.githubusercontent.com/1575452/38764642-92ecd5ae-3f78-11e8-8762-cba9826c3190.png">

**Comment by jorgheymans** [comment]
workaround is to declare the fully qualified proto path it seems for the import, so in your case `import "Authentication/Server/Service/Base.proto"`
