### ISSUE TITLE
"Import" does not work properly when I provide "package" keyword. 

### ISSUE THREAD

**Issue by P-A-R-U-S** [protostuff/protobuf-jetbrains-plugin#98]
Based on photo 3 [https://developers.google.com/protocol-buffers/docs/proto3#packages](url), but looks like plugin not handle "package" and "import" options at the same file. Please, two screenshot below. At first one "import" option handled properly and second one when after adding "package" option File Not Found message are shown on the screen. 

<img width="895" alt="screen shot 2018-04-14 at 12 10 47 am" src="https://user-images.githubusercontent.com/1575452/38764659-ce7ff40c-3f78-11e8-90e8-1764e45f4fae.png">
<img width="927" alt="screen shot 2018-04-14 at 12 11 01 am" src="https://user-images.githubusercontent.com/1575452/38764661-d2486c90-3f78-11e8-9482-6b93cd9e8b20.png">

**Comment by TRBaldim** [comment]
Yes this is happening with me as well. This is really annoying.

**Comment by gak** [comment]
This might sound bizarre, but this worked for me:

1) Make sure the protobuf custom include path is configured in the settings (mentioned in the README)
2) Comment out the package line, wait until import is not an error, then uncomment.

**Comment by TRBaldim** [comment]
The one that I'm using is the most recent (0.10.2). 
<img width="775" alt="screen shot 2018-06-19 at 10 03 05 am" src="https://user-images.githubusercontent.com/3915454/41568265-111fe0ac-73a8-11e8-8f51-15b4681e2622.png">

**Comment by TRBaldim** [comment]
@gak Even with the full path we have error with proto3. Proto2 works well but the version 3 is broken.
<img width="356" alt="screen shot 2018-06-19 at 10 06 07 am" src="https://user-images.githubusercontent.com/3915454/41568346-8300f9e0-73a8-11e8-9c04-197a1df12ff0.png">

**Comment by geekmdtravis** [comment]
Just bringing light to the issue by noting I am seeing this error as well. It's quite distracting. Presently I have to comment out the package name to work on the file, or go to VSCode :/ 

Minimal case here:
![goland_protobuf_plugin_error](https://user-images.githubusercontent.com/41837536/43371197-f87b1d5a-9341-11e8-81a0-e2517b434ce9.png)
